PRODUCT_NAME = "NoahPress"
PRODUCT_VERSION = "1.0.0"
MAIN_WINDOW_WIDTH = 1024
MAIN_WINDOW_HEIGHT = 600
SCROLL_SIZE = 24

COLOR_WHITE = "#ffffff"
ONE_INCH_MM = 25.4

MESSAGE_IS_EDIT = "編集中の内容は破棄されます。よろしいですか?"
